# Generated by Django 6.0.1 on 2026-02-14 22:31

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=builtins.id),
        ),
    ]
