# Generated by Django 6.0.1 on 2026-02-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0009_country_alter_address_options_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publised_country',
            field=models.ManyToManyField(to='book_outlet.country'),
        ),
    ]
